site_name: Dmitry Tsybus / Notes
site_url: https://notes.ditsi.ru
plugins:
  - search:
  - exclude:
      glob:
        - "ansible/*"

extra:
  analytics:
    provider: google
    property: G-0K7SE0P6FC

theme:
  name: material
  features:
    - search-suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.tabs
    - header.autohide
